desc: Watch go files for changes
triggers:
- name: "server"
  pattens:
  - '**/*.go'
  - '!vendor/**/*'
  - '!frontend/**/*'
  env:
    DEBUG: "1"
  cmd: go run cmd/bookmarks/bookmarks.go
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- .
watch_depth: 2
