desc: Watch go files for changes
triggers:
- name: "server"
  pattens:
  - '**/*.go'
  - '!vendor/**/*'
  - '!frontend/**/*'
  env:
    DEBUG: "1"
  cmd: go run -ldflags "-X main.Version=-1" cmd/bookmarks/bookmarks.go -workers 1 -debug -database .git/run/data.sqlite
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- .
watch_depth: 2
